### ISSUE TITLE
Support more include patterns

### ISSUE THREAD

**Issue by martis42** [martis42/depend_on_what_you_use#11]
The [known limitations](#Known-limitations) are caused by the complexity of all possible ways to include a header in C++.
The complexity is caused mainly by the preprocessor which allows dynamically adding include statements through macros and to enable/disable includes based on defines.

We could reimplement the preprocessor logic inside DWYU to support more complex include patterns.
The benefit would be that DYWU remains self-contained without external dependencies.
However, this would also be reinventing the wheel.
The C preprocessor is an old problem which has been solved many times until now.
Trying to implement and test a C preprocessor solely for the sake of prevent third party dependencies is wasteful.
The world does not need yet another C Preprocessor.

No design how to proceed has been made up yet.

The following tools could be part of the solution if we want to keep Python as implementation language:
* https://pypi.org/project/pcpp/
* https://github.com/paulross/cpip
* https://github.com/eliben/pycparser
* https://eli.thegreenplace.net/2011/07/03/parsing-c-in-python-with-clang

We could also move the implementation to C++.
The LLVM toolchain is a quite powerful toolset and allows interaction with the preprocessor.
See for example https://clang.llvm.org/doxygen/classclang_1_1Preprocessor.html#details.
LLVM is however not a lightweight dependency and having to compile DWYU will reduce its portability.

~~Yet another possibility is telling the compiler to generate a `.d` file, which lists the includes required for a given source file.
This provides an easy to parse output listing all include statements which are required after resolving macros and defines.
However, a first test shows all transitive headers are resolved.
This is a problem, since we need to know the include statements for the file under inspection, but not more.
If all transitive includes are listed as well, we cannot compare this list to the direct dependencies.
It is not yet known if this behavior can be modified.~~
https://github.com/martis42/depend_on_what_you_use/commit/6fb152ff263eee0b746f9f9fc628066e67285ae6

**Comment by martis42** [comment]
Could also be part of the solution: https://github.com/llvm/llvm-project/blob/main/clang/bindings/python/examples/cindex/cindex-includes.py

**Comment by storypku** [comment]
> Could also be part of the solution: https://github.com/llvm/llvm-project/blob/main/clang/bindings/python/examples/cindex/cindex-includes.py
> 
> https://github.com/Moecker/samo_tidy/blob/main/samo_tidy/utils/clang_setup.py#L13

Hi @martis42 ,
I have done some investigation and experiments with Clang Python bindings. It works fine and can get all enabled includes controlled by defines. Ref:  https://github.com/storypku/depend_on_what_you_use/tree/conditional_includes/experimental/conditional_includes

**Comment by martis42** [comment]
@storypku 
Thanks for experimenting with `clang.cindex` :smiley: That it seems to work as expected is wortwhile feedback.

However, at the moment I am not sure if clang will indeed be the future of this project.
Clang is a heavy dependency. Also it reduces the uniqueness of DWYU. Some of what DWYU does it by now supported by standard Bazel, if one uses clang. See https://github.com/martis42/depend_on_what_you_use/issues/70.

I am contemplating if a Python only approach might be better. Yes, then one will not be able to parse all possible code edge cases allowed by the C++ standard. But, DWYU then has the distinguishing feature of not requiring a compiler.

That much said, nothing has been decided yet. This is just something I am thinking about every now and then. Improving the automatic fixes and extending and streamlining the test cases will be my priority for now. Better testing is either way required before doing any large changes.

**Comment by storypku** [comment]
@martis42 
Thank you for sharing your thoughts on the future of DWYU. 
I agree with you that Clang is a heavy dependency and depending on it will reduce the portability of DWYU. A "pure" python approach would be better to get "correct" includes if possible.
However, conditional includes is common in C++ projects, and we should take seriously of it. Specifying all relevant deps for conditional includes is not a good practice and some times even not feasable. E.g.,

```
cc_library(name = "windows", target_compatible_with = ["@platforms//os:windows"])
cc_library(name = "linux", target_compatible_with = ["@platforms//os:linux"]),

cc_binary(name = "platform_dependent_binary", deps = [":windows", ":linux"])
```

I noticed the layering_check feature you mentioned in DWYU's top-level README.md and #70. And I want to share my two-cents:

1. Not every Bazel user is a Clang user. There are many GCC/ICC/... compiler users in the Bazel community. Not to mention some features DWYU supports were not present in Clang/Bazel yet.
2. Everything is a historical product, so do DWYU. Suppose that one day Bazel support the DWYU feature out-of-box, or C++ has evolved  to completely abandon `#include` ([C++-20](https://en.cppreference.com/w/cpp/language/modules)), then we can sunset this project. Before that, DWYU remains useful and relevent. Maybe before that, DWYU has evolved into other form(s). The spirit of Use-What-You-Need, reflecting software engineers' persuits of simplicity, will always  shines.

**Comment by storypku** [comment]
And, I do apprecate your priority in improving the automatic fixes feature and extending testcases. I will advocate the use of DWYU across my company and may report more issues (w/ or w/o PRs)  for you.

Meanwhile, I will maintain a seprate branch on supporting the conditional includes feature, whether or not Clang Python bindings is used to parse C++ code. Once that's ready,  we can discuss more here.

**Comment by martis42** [comment]
@storypku 

> However, conditional includes is common in C++ projects, and we should take it seriously

Full agreement from my side.
Assuming I decide to keep DWYU pure Python, then this means the self written logic for parsing source files has to improve.
At minimum one should be able to process defines which are set through Bazel. This would be trivial from a function logic point of view. The aspect knows all defines which are coming from the command line or are set in the `cc_*` target attributes. We already parse the source files line by line. Including the logic to handle `#ifdef` and similar should be manageable.
The harder problem is if a header A defines some value and it is used in header B for ifdef logic. This requires processing the files in correct order. Still doable, but already a more complex thing and then one really has to decide, "do I want to reinvent the wheel to keep the project standalone"?

Essentially we are talking about 2 alternatives
1. Use some preprocessor to completely parse the code like a compiler would. Given the preprocessor is correct and allows inspecting all information desired by DWYU this should solve all header parsing issues. Due to depending on the same underlying tool (clang), DWYU is like some kind of extended layering check.
2. Use only Python to parse the header. Most likely we will never support all header inclusion edge cases. But we are highly portable and work without any predecessor or compiler. Also DWYU has a strong separation point from Bazels layering check (among others). At least processing defines which are known to Bazel would be supported eventually.

> Not every Bazel user is a Clang user. There are many GCC/ICC/... compiler users in the Bazel community 

This is exactly my point. By not relying on clang DWYU is especially useful for those developers. By depending on clang, or a specific compiler in general, the tool is less attractive to those not using clang. We would not have to use clang as full compiler, but could use it as library helping us analyze the code. Still, for the platform one is working on there have to be pre-compiled clang binaries available, unless we want to start building clang from source.

**Comment by martis42** [comment]
The strategy for now is using [pcpp](https://pypi.org/project/pcpp/)
By now we use `pcpp` to implement a basic parsing of defines: https://github.com/martis42/depend_on_what_you_use/pull/118

The main alternatives which have been considered at the end have been pcpp and using clang via cindex.

Some reasons for choosing pcpp are:
- Bazels standard clang toolchain supports the `layering_check` feature, which offers similar features like DWYU (for a comparison see [here](https://github.com/martis42/depend_on_what_you_use#alternatives-to-dwyu)). Relying on clang as well reduces the distinction of DWYU compared to upstream Bazel.
- While [libclang](https://pypi.org/project/libclang/) offers a clang Python binding which does not require a host clang installation, it is still limited to to specific set of platforms for which wheels are provided.
- `pcpp` is easy to use and elegantly allows customizing the preprocessor behavior.
- Even if it turns out eventually that pcpp is not sufficient to support all required use cases. We can at any point switch to another preprocessor implementation and still reuse all the supporting code in the aspect and the integration tests. For now I feel most comfportable using `pcpp` as preprocessor.
