### ISSUE TITLE
Use the tag `no-dwyu` to opt out of DWYU on specific targets

### ISSUE THREAD

**Issue by freeformstu** [martis42/depend_on_what_you_use#123]
Hi, I'd like to propose using the tag `no-dwyu` to allow opting out of DWYU on specific targets.

We use some external dependencies which do not work with dwyu.

It would be extremely useful to be able to opt out of these checks for a few targets while still getting the benefits for all other targets.

**Comment by martis42** [comment]
Hi @freeformstu ,
thanks for the contribution together with this request :)

The request makes sense to me and I will have a look at your PR in a minute.

Could you please help me better understand your use case? Are you using the recursive mode of the aspect? If you work without recursion you could also simply use negative target patterns for ignoring targets.

**Comment by martis42** [comment]
Thanks for this detailed answer!
I understand the use case of performing multiple actions on a specific target set and thus negative patterns being not a proper solution. I believe a tag is indeed a proper solution here.

Regarding the includes from headers generated by rules_hdl not being analyzed correctly. I was not yet aware of rules_hdl until now, but I am aware of the general problem. DWYU is not yet able to work with code modeled as TreeArtifact.
I started working on that, but did not solve the issue yet.

**Comment by freeformstu** [comment]
I'm happy to close this issue out now that the associated PR has been merged. Thanks for the fast code review!
