### ISSUE TITLE
Support Tree Artifacts

### ISSUE THREAD

**Issue by martis42** [martis42/depend_on_what_you_use#135]
Code generators often use tree artifacts to model their outputs.
DWYU should support those as well.

**Comment by matte1** [comment]
Sorry I'm not sure I fully grok the above but maybe I can throw my issue here too and see if it fits?

Its pretty common for us to generate code / cc targets from a bazel rule that then gets used in handwritten code / cc targets. DWYU seems to break on these use cases. I'm happy to help contribute here if you can point me in the write direction?

**Comment by martis42** [comment]
@matte1 
There are 2 cases of generators

### code generation with known output

This should work with DWYU. If it does not for you, please provide a minimal example as bug.

pseudo code example:
```
def my_macro(name):
  some_action_generationg_files(
  out_hdr = "foo",
  out_src = "bar",
  )

  native.cc_library(
  name = name,
  srcs = ["bar"],
  srcs = ["foo"],
  )
```

Alternative a rule could generate code and take care of compilation itself and provide a CcInfo output. This should work as well.

### code generators with unknown output

This boils down to the generator rule using `ctx.actions.declare_directory()` to generate the output. This is the case, when the files one is generating are not known upfront (e.g. determined by an input file). Thus, one creates a directory with an arbitrary amount of files in it as output. This directory is called `TreeArtifact`
Unfortunately, `TreeArtifact` is poorly documented and behaving different then created single files.
Riht now DWYU does not support `TreeArtifact` targets, but I am working on it.

**Comment by martis42** [comment]
@matte1 
I just finished my work on the initial support for `TreeArtifact` based code generators.
You can use the [latest release](https://github.com/martis42/depend_on_what_you_use/releases/tag/0.0.10) to check out of this helps you. If not please provide a bug report.

**Comment by martis42** [comment]
@matte1 
Thanks for clarifying.
Actually, DWYZ supports targets which use `includes = [...]`.
It seems you found a bug. Would you please open a new issue and provide a minimal example for your case? Then I will gladly fix it.
