### ISSUE TITLE
Action failed, file name to long

### ISSUE THREAD

**Issue by mnil** [martis42/depend_on_what_you_use#151]
We are bumping to 0.0.11 and getting failures due to too long file names on Linux. The following is the file that is causing the issue:

```
src/aspect/dwyu.bzl:
output_path = "{}_processed_dep_{}.json".format(_label_to_name(target.label), _label_to_name(dep.label)),

Action <redacted>.json failed: failed to delete output files before executing action: <redacted>.json 
```

would it be possible to find a unique filename that is not as long?

**Comment by martis42** [comment]
@mnil 
The issue should be resolved.
I deployed a new release which contains the fix: https://github.com/martis42/depend_on_what_you_use/releases/tag/0.0.12

**Comment by mnil** [comment]
Thanks for the quick fix, I can confirm that it works on our targets now!
