### ISSUE TITLE
Automatic Fixes - Suggest direct dependency for transitively used header

### ISSUE THREAD

**Issue by martis42** [martis42/depend_on_what_you_use#18]
Continuation for the automatic fixes feature from https://github.com/martis42/depend_on_what_you_use/issues/10

When detecting a header which is not available from a direct dependency query the workspace for the target providing the header and suggest using it.

**Comment by storypku** [comment]
Looking forward to this feature. I am using self-written `header_query` program which was essentially a `bazel query attr('hdrs', 'path/to/header.h`, //...:*)` or `bazel query attr('hdrs', 'path/to/header.h`, @external_repo//...:*)` call. However, there are a few issues with this approach.
1. How we "route" given header to the relevant `external_repo`? 
2. There maybe multiple targets "exporting" the given header. And the `visible(//my/path, "@external_repo//package:target)` may both return OK. 
E.g., 

```
$ header_query gflags/gflags.h
Multiple target containing header 'gflags/gflags.h'. They are:
  '@com_github_gflags_gflags//:gflags_nothreads'
  '@com_github_gflags_gflags//:gflags'
```

3. `bazel query attr('hdrs', 'path/to/header.h', @external_repo//...:*)` may fail as not all dependencies of external_repo exists.

```
$ bazel query "attr('hdrs', 'grpc++/grpc++.h', @com_github_grpc_grpc//...:*)"
ERROR: error loading package '@com_github_grpc_grpc//examples/python/errors': Unable to find package for @grpc_python_dependencies//:requirements.bzl: The repository '@grpc_python_dependencies' could not be resolved.
Loading: 20 packages loaded
    currently loading: @com_github_grpc_grpc//examples/protos ... (4 packages)
    Fetching @bazel_toolchains; fetching
```
