### ISSUE TITLE
seeing false reports of non unique headers.

### ISSUE THREAD

**Issue by gedalia** [martis42/depend_on_what_you_use#237]
seeing errors of the form:
Found multiple targets which potentially can provide include 'rt/libs/libspatial/mechanisms/ids.h' of target '@//rt/libs/libtrackingutils/state_trajectory_tracking:kcmpc'.
Please fix this manually. Candidates which have been discovered:
- //rt/libs/libkalman2:libkalman2
- //rt/libs/libspatial/mechanisms:ids
It seems like the code might be confused, there are two header files named ids.h but they are each included with fully qualified paths, seems like the code might be missing that fact.

**Comment by martis42** [comment]
@gedalia 
Thanks for the detailed feedback :medal_sports: 

You are not the first to hit performance problems for massive bazel output directories (see https://github.com/martis42/depend_on_what_you_use/issues/217)
I will think about your idea to store a report making the workspace crawling superfluous. Actually this would also help with the many ways DWYU needs to support to point to the correct workspace.

> I think we had procedurally generated headers from protobuf generation that it missed, and we had a header file only target that I think the tool wound up stripping out the associated obj library and we failed static linking, that might just be a bad pattern on our side.

Could you provide a minimal example for this? Would like to look into both issues.

> Lastly I think buldozer stripped out some OS specific selects that was a surprise.

One thing I can think of is that right now the apply_fixes logic is based on `bazel query` and  no option exists yet to use `cquery` instead. Still, it surprises me the commands generated by the apply_fixes script remove select statements.
Could you provide a minimal example for this as well?

If you find the time to provide examples, could you please put them into dedicated issues.

**Comment by martis42** [comment]
@gedalia The fix for your main issue is now part of a proper release: https://github.com/martis42/depend_on_what_you_use/releases/tag/0.2.0

**Comment by gedalia** [comment]
Thank you, I got retasked to a different project, but will hopefully have some time to take a look at the system again in the coming weeks.

**Comment by gedalia** [comment]
Thank you, hopefully I'll have a chance to take another look in the future.
