### ISSUE TITLE
Missing STD headers

### ISSUE THREAD

**Issue by TendTo** [martis42/depend_on_what_you_use#261]
While running the newer version of the tool, I started getting a lot of errors about std libraries I did not receive before.

Looking at the implementation, I see that the list of libraries should be taken from 

https://github.com/martis42/depend_on_what_you_use/blob/ee7e0370f01badecd7de5a009c390859b6145c98/src/analyze_includes/std_header.py#L3

But the, actual list

https://github.com/martis42/depend_on_what_you_use/blob/ee7e0370f01badecd7de5a009c390859b6145c98/src/analyze_includes/std_header.py#L13

is missing a lot of the standard headers, from more recent ones like `string_view` to older ones like `unordered_map`.

It seems that [this commit](https://github.com/martis42/depend_on_what_you_use/commit/b733ec571ff13e1bd6e53e66bb3a683e3223ef8d) is the culprit.
Unless there is a specific reason for this change I'm missing, would it be possible to add the std libraries that are now absent?

**Comment by martis42** [comment]
Thanks for this report.
This was a stupid error by me. Due to an error in the script creating this header list all header using an `_` are missing. A fix will come shortly.

**Comment by martis42** [comment]
@TendTo The fix has been released via version 0.4.0.
