### ISSUE TITLE
How relevant is DWYU  anymore?

### ISSUE THREAD

**Issue by martis42** [martis42/depend_on_what_you_use#70]
It seems one can perform the analysis of "using private headers" and "using headers from transitive dependencies" also by simply using the clang compiler with some specific settings: https://maskray.me/blog/2022-09-25-layering-check-with-clang

Bazel offers easy access to this through the `layering_check` feature of the default toolchain
- [layering_check](https://github.com/bazelbuild/bazel/blob/b272cef7d4b2d1be4e3f82b737c3c14d5e768aea/tools/cpp/unix_cc_toolchain_config.bzl#L65)
- https://github.com/bazelbuild/bazel/issues/17055

Example usage: `bazel build --verbose //:foo --repo_env=CC=clang --features=layering_check`

**Comment by dmeister** [comment]
I only started using DMYU recently, but there are still a few aspects that I value: 1) using clang in my environment is quite tricky 2) the automatic fixing feature of DWYU is something that the layering_check doesn't yet provide (as far as I understand).

**Comment by martis42** [comment]
I am happy DWYU is a helpful tool for you :)

Finding unused dependencies is another thing layering_check seems unable to do.
