### ISSUE TITLE
get_includes_from_file failed to parse includes for some cases

### ISSUE THREAD

**Issue by storypku** [martis42/depend_on_what_you_use#86]
The `get_includes_from_file` function from [parse_source.py](https://github.com/martis42/depend_on_what_you_use/blob/main/src/analyze_includes/parse_source.py#L42) will fail to find include for the following line:

```
/* commented out */ #include "abc.h" /* commented out */
```

Although such use case is rare.

**Comment by storypku** [comment]
How ever the following line will fail either, and it's not uncommon 

```
#include <cstring> /* for strcmp */
```

We should fix this even before using libclang to parse includes.

**Comment by martis42** [comment]
Resolved by https://github.com/martis42/depend_on_what_you_use/pull/87
